name: 'Get an app token in an Actions workflow.'
description: GitHub action that retrieves a GitHub app token using its private key, ID and installation ID.
author: Flutter Tech
inputs:
  APP_PEM:
    description: PEM key used to authenticate as a GitHub App.
    required: true
  APP_ID:
    description: GitHub App ID.
    required: true
  APP_INSTALLATION_ID:
    description: GitHub App installation ID.
    required: true
outputs:
  app_token:
    description: The installation access token for the GitHub App.
runs:
  using: 'docker'
  image: 'Dockerfile'